version: '3'
services:

  zookeeper:
    container_name: zookeeper
    restart: unless-stopped
    image: wurstmeister/zookeeper

  kafka:
    container_name: kafka
    restart: unless-stopped
    image: wurstmeister/kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost
    depends_on:
      - zookeeper

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql